spring.config.activate.on-profiles: valid

valid:
  password:
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!])(?=\\S+$).{8,}$"
    message:
      empty: 비밀번호는 공백일 수 없습니다.
      err: 비밀번호는 최소 8자 이상, 영문 대소문자, 숫자, 특수 문자 포함해야 합니다.